name: 'xero_source'
version: '0.3.0'
config-version: 2
require-dbt-version: ">=0.20.0"

vars:
  xero_source:
    account: "{{ source('xero','account') }}"
    journal_line: "{{ source('xero','journal_line') }}"
    journal: "{{ source('xero','journal') }}"
    invoice: "{{ source('xero','invoice') }}"
    invoice_line_item: "{{ source('xero','invoice_line_item') }}"
    contact: "{{ source('xero','contact') }}"
    organization: "{{ source('xero','organization') }}"
    bank_transaction: "{{ source('xero','bank_transaction') }}"
    credit_note: "{{ source('xero','credit_note') }}"
    purchase_order: "{{ source('xero','purchase_order') }}"
    purchase_order_line_item: "{{ source('xero','purchase_order_line_item') }}"

models:
  xero_source:
    +materialized: table
    +schema: stg_xero
    tmp:
      +materialized: view
