name: 'xero_source'
version: '0.1.0'
config-version: 2
require-dbt-version: [">=0.19.0", "<0.20.0"]

vars: 
  xero_source:
    account: "{{ source('xero','account') }}"
    journal_line: "{{ source('xero','journal_line') }}"
    journal: "{{ source('xero','journal') }}"
    invoice: "{{ source('xero','invoice') }}"
    invoice_line_item: "{{ source('xero','invoice_line_item') }}"
    contact: "{{ source('xero','contact') }}"
    organization: "{{ source('xero','organization') }}"