version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.7.9-stretch

    steps:
      - checkout

      - run:
          run: setup_creds
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
      - run:
          name: "Setup dbt"
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip setuptools
            pip install -r integration_tests/requirements.txt
            mkdir -p ~/.dbt
            cp integration_tests/ci/sample.profiles.yml ~/.dbt/profiles.yml
      - run:
          name: "Run Tests - Redshift"
          command: |
            . venv/bin/activate
            echo `pwd`
            export DBT_PACKAGE_TEST=redshift
            cd integration_tests
            dbt deps
            dbt seed --full-refresh
            dbt run --full-refresh
            dbt test
            sqlfluff lint models --dialect postgres
      - run:
          name: "Run Tests - Postgres"
          command: |
            . venv/bin/activate
            echo `pwd`
            export DBT_PACKAGE_TEST=postgres
            cd integration_tests
            dbt deps
            dbt seed --full-refresh
            dbt run --full-refresh
            dbt test
            sqlfluff lint models --dialect postgres
      - run:
          name: "Run Tests - Snowflake"
          command: |
            . venv/bin/activate
            echo `pwd`
            export DBT_PACKAGE_TEST=snowflake
            cd integration_tests
            dbt deps
            dbt seed --full-refresh
            dbt run --full-refresh
            dbt test
            sqlfluff lint models --dialect snowflake
      - run:
          name: "Run Tests - BigQuery"
          environment:
              GCLOUD_SERVICE_KEY_PATH: "/home/circleci/gcloud-service-key.json"

          command: |
            . venv/bin/activate
            echo `pwd`
            export DBT_PACKAGE_TEST=bigquery
            cd integration_tests
            dbt deps
            dbt seed --full-refresh
            dbt run --full-refresh
            dbt test
            sqlfluff lint models --dialect bigquery